AWSTemplateFormatVersion: "2010-09-09"

Resources:

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: my-instance-profile
      Path: /
      Roles: 
       - WebServerRole

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        IamInstanceProfile: 
          Name: my-instance-profile
        ImageId: ami-051a81c2bd3e755db
        InstanceType: t2.nano
        KeyName: TestAws
        SecurityGroupIds:
          - sg-074fcfbff1ffe1ccd
        UserData: !Base64 |
          #!/bin/bash

          set -x
          cd /home/ec2-user
          echo "hello" > /home/ec2-user/test.txt
          yum update -y
          yum install -y ruby wget
          wget https://aws-codedeploy-ap-southeast-2.s3.ap-southeast-2.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto

  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate:
        LaunchTemplateName: MyLaunchTemplate
        Version: 1
      Tags:
        - Key: app
          Value: test
        - Key: user
          Value: ab